'use strict';

/**
 * @file engine.js
 * @description Core Security Orchestrator for ShieldWall WAF.
 * Acts as the primary decision engine unifying signatures, behavioral heuristics, and rate limiting.
 *
 * @dependencies
 * - `decoder.js`: Input normalization payload unpacking.
 * - `rule-parser.js` & `rule-matcher.js`: YARA-inspired signature evaluation.
 * - `reputation.js`: Time-decaying threat intelligence store (used for FP Circuit Breakers).
 * 
 * @flow
 * 1. Intakes raw HTTP requests (`req`).
 * 2. `_extractIP`: Computes real IP handling proxy topologies.
 * 3. `decodeRequest`: Unrolls encodings (URL, base64, HTML entities).
 * 4. Extracts Signals: Runs Detectors concurrently (Modules + .shield rules).
 * 5. Risk Aggregation: Combines signals weighted by Action Sensitivity (Context).
 * 6. Circuit Breaker: Evaluates history to prevent False Positives for established users.
 * 7. Policy Enforcement: Blocks or logs.
 */

const { EventEmitter } = require('events');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { decodeRequest } = require('./decoder');
const { parseRules, loadRulesFromDir } = require('./rule-parser');
const { matchAllRules } = require('./rule-matcher');
const Logger = require('./logger');
const ReportingEngine = require('./reporting');

const DEFAULT_RULES_DIR = path.join(__dirname, '..', '..', 'rules');
const SEVERITY_PRIORITY = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
const SEVERITY_WEIGHTS = { critical: 100, high: 50, medium: 20, low: 10, info: 1 };
const MAX_AUTO_RULES = 50;
const AUTO_RULE_TTL_DAYS = 7;

/**
 * Action Sensitivity Context Matrix
 * Multiplies anomaly scores based on the operational severity of the endpoint.
 * Protects against False Positives generated by noisy interaction on low-risk public pages.
 */
const ENDPOINT_SENSITIVITY = [
  { pattern: /^\/(auth|login|register|reset-password|oauth|sso)/i, multiplier: 2.5 },
  { pattern: /^\/(admin|cms|wp-admin|dashboard|control-panel)/i, multiplier: 3.0 },
  { pattern: /^\/api\/v[0-9]+\/(payment|checkout|cart|billing)/i, multiplier: 2.0 },
  { pattern: /^\/(search|catalog|public|assets|_next|static)/i, multiplier: 0.2 },
  { pattern: /.*/, multiplier: 1.0 }
];

class ShieldWallEngine extends EventEmitter {
  /**
   * Initializes the WAF Engine.
   * @param {Object} options - Configuration options.
   * @param {string} options.mode - 'block' | 'log'.
   * @param {boolean} options.trustProxy - Required to securely parse X-Forwarded-For.
   */
  constructor(options = {}) {
    super();

    this.options = {
      mode: options.mode || 'block',
      logLevel: options.logLevel || 'info',
      jsonLogs: options.jsonLogs || false,
      silent: options.silent || false,
      rulesDir: options.rulesDir || DEFAULT_RULES_DIR,
      customRules: options.customRules || null,
      customRulesFiles: options.customRulesFiles || [],
      blockStatusCode: options.blockStatusCode || 403,
      blockMessage: options.blockMessage || null,
      trustProxy: options.trustProxy || false,
      excludePaths: options.excludePaths || [],
      excludeIPs: options.excludeIPs || [],
      blockThreshold: options.blockThreshold || 100,
      modules: {
        anomaly: true, smartAnomaly: true, honeypot: true,
        pathTraversal: true, commandInjection: true,
        botDetection: true, sessionAnomaly: true, apiAbuse: true,
        ddosProtection: true, fingerprinter: true, reputation: true,
        ...(options.modules || {}),
      },
      autoGenerateRules: options.autoGenerateRules !== false,
    };

    this._autoGeneratedHashes = new Set();
    this.logger = new Logger({
      level: this.options.logLevel,
      silent: this.options.silent,
      json: this.options.jsonLogs,
      maxHistory: options.maxHistory || 10000,
      onEvent: (event) => this.emit('log', event),
    });

    this.rules = [];
    this._loadRules();

    this.modules = [];
    this._loadModules();

    this.stats = { totalRequests: 0, blockedRequests: 0, detectedThreats: 0, startTime: Date.now() };

    this.reporting = null;
    if (options.reporting !== false) {
      this.reporting = new ReportingEngine({
        enabled: true,
        reportsDir: options.reportsDir,
        maxStoredReports: options.maxStoredReports,
        logger: this.logger,
        onReport: (report) => this.emit('report', report),
      });
    }

    this.logger.info('Engine initialized', {
      mode: this.options.mode,
      rulesLoaded: this.rules.length,
      modulesActive: this.modules.map(m => m.name),
    });
  }

  /**
   * Resolves the true client IP safely, accounting for reverse proxies.
   * Prevents Proxy Blindness bugs where 'req.ip' maps to Cloudflare or a Load Balancer.
   * @param {Object} req - Inbound HTTP request.
   * @returns {string} The canonical client IP address.
   */
  _extractIP(req) {
    if (this.options.trustProxy && req.headers && req.headers['x-forwarded-for']) {
      // Parse multi-tier proxies, grabbing the original public client
      const ips = req.headers['x-forwarded-for'].split(',').map(ip => ip.trim());
      if (ips.length > 0) return ips[0];
    }
    return req.ip || req.connection?.remoteAddress || req.socket?.remoteAddress || 'unknown';
  }

  /**
   * Initializes YARA-like rule payloads from the filesystem and inline configs.
   */
  _loadRules() {
    try {
      this.rules.push(...loadRulesFromDir(this.options.rulesDir));
    } catch (err) {
      this.logger.warn(`Could not load default rules: ${err.message}`);
    }

    for (const filePath of this.options.customRulesFiles) {
      try {
        const { parseRuleFile } = require('./rule-parser');
        this.rules.push(...parseRuleFile(filePath));
      } catch (err) {
        this.logger.error(`Error loading rules from ${filePath}: ${err.message}`);
      }
    }

    if (this.options.customRules) {
      try { this.rules.push(...parseRules(this.options.customRules)); }
      catch (err) { this.logger.error(`Error parsing inline rules: ${err.message}`); }
    }
  }

  /**
   * Dynamically loads heuristic detection modules into the analysis pipeline.
   */
  _loadModules() {
    const map = {
      anomaly: '../modules/anomaly',
      smartAnomaly: '../modules/smart-anomaly',
      honeypot: '../modules/honeypot',
      pathTraversal: '../modules/path-traversal',
      commandInjection: '../modules/command-injection',
      botDetection: '../modules/bot-detection',
      sessionAnomaly: '../modules/session-anomaly',
      apiAbuse: '../modules/api-abuse',
      ddosProtection: '../modules/ddos-protection',
      fingerprinter: '../modules/fingerprinter',
      reputation: '../modules/reputation',
    };

    for (const [name, modulePath] of Object.entries(map)) {
      if (!this.options.modules[name]) continue;
      try {
        const mod = require(modulePath);
        this.modules.push({ name, check: mod.check, module: mod });
      } catch (err) {
        // Suppressing deeply nested crashes to prevent halting the entire boot process.
        this.logger.warn(`Module "${name}" not loaded: ${err.message}`);
      }
    }
  }

  /**
   * Central evaluation loop: Processes the request against all security layers.
   * @param {Object} req - The raw HTTP request object.
   * @returns {Promise<Object>} The verdict map including { blocked, matches, riskScore }.
   */
  async analyze(req) {
    this.stats.totalRequests++;
    
    // Dynamically patch the core IP address on the request before downstream handling
    req.clientIp = this._extractIP(req);

    if (this._isExcluded(req)) return { blocked: false, matches: [], decodedReq: null, riskScore: 0 };

    // Deep Decode Payload (Removes traversal evasion attempts)
    const decodedReq = decodeRequest(req);
    // Sync the patched IP into the decoded request state
    decodedReq.ip = req.clientIp;

    const allMatches = [];

    // Parallel execution slice: All detectors evaluate simultaneously 
    const modulePromises = this.modules.map(async (mod) => {
      try {
        return await mod.check(decodedReq);
      } catch (err) {
        this.logger.error(`Detector "${mod.name}" failure: ${err.message}`);
        return null; // Silent catch: Resilient pipeline design ensures one failing module doesn't crash WAF
      }
    });

    const moduleResults = await Promise.all(modulePromises);
    for (const results of moduleResults) {
      if (results?.length) allMatches.push(...results);
    }

    allMatches.push(...matchAllRules(this.rules, decodedReq));

    // Fast fail check: Save CPU if payload is fully clean
    if (!allMatches.length) return { blocked: false, matches: [], decodedReq, riskScore: 0 };

    /**
     * RISK AGGREGATION ENGINE (Deep Dive)
     * Maps extracted anomaly signals against Endpoint Complexity Constraints.
     */
    const sensitivity = this._getEndpointSensitivity(decodedReq.path || decodedReq.url || '');
    let cumulativeRiskScore = 0;
    
    for (const match of allMatches) {
      let baseCost = 0;
      if (typeof match.score === 'number' && match.score > 0) {
        baseCost = match.score;
      } else {
        baseCost = SEVERITY_WEIGHTS[match.severity] || 0;
      }
      cumulativeRiskScore += (baseCost * sensitivity);
    }

    let dynamicBlockThreshold = this.options.blockThreshold;

    /**
     * FALSE POSITIVE: CIRCUIT BREAKER
     * We dynamically discount the risk threshold if this user has established Trust.
     * Prevents IP drift and noisy double-click bans on validated users.
     */
    if (this.options.modules.reputation !== false) {
      try {
        const { getReputation } = require('../modules/reputation');
        const userRep = getReputation(decodedReq.ip);
        
        // If they have 0 incidents and their history spans more than 6 hours, give them leeway
        if (userRep.score === 0 && userRep.firstSeen) {
           const historyHours = (Date.now() - userRep.firstSeen) / (1000 * 60 * 60);
           if (historyHours > 6) {
              dynamicBlockThreshold = Math.floor(dynamicBlockThreshold * 1.5); // 50% leniency bonus (Circuit Breaker)
           }
        }
      } catch (e) {
        // Suppress reputation link errors
      }
    }

    const blocked = this.options.mode === 'block' && cumulativeRiskScore >= dynamicBlockThreshold;
    const highestSeverity = this._getHighestSeverity(allMatches);

    for (const match of allMatches) {
      this.logger.attack({
        blocked,
        rule: match.rule,
        severity: match.severity,
        category: match.category,
        ip: decodedReq.ip,
        method: decodedReq.method,
        url: decodedReq.rawUrl,
        description: match.description,
        matchedPattern: this._formatEvidence(match),
        analysis: match.analysis || null,
      });

      if (this.options.modules.reputation !== false) {
        try {
          const { record } = require('../modules/reputation');
          record(decodedReq.ip, match.category, match.severity);
        } catch {}
      }

      this._generateAutoRule(match, decodedReq);
    }

    this.stats.detectedThreats += allMatches.length;
    if (blocked) this.stats.blockedRequests++;

    this.emit('threat', {
      blocked, matches: allMatches, highestSeverity, riskScore: cumulativeRiskScore,
      request: { ip: decodedReq.ip, method: decodedReq.method, url: decodedReq.rawUrl, userAgent: decodedReq.userAgent },
    });

    return { blocked, matches: allMatches, decodedReq, highestSeverity, riskScore: cumulativeRiskScore };
  }

  /**
   * Formats the attack evidence structure mapping for Kibana/Datadog dashboards.
   * @param {Object} match - The hit result from a detector.
   * @returns {string} Stringified payload excerpt.
   */
  _formatEvidence(match) {
    if (match.analysis?.factors) {
      return match.analysis.factors.map(f => `[${f.name}] ${f.detail}`).join(' | ');
    }
    if (match.matchedPatterns?.length) {
      return match.matchedPatterns.map(p => `${p.name}: "${p.matched}"`).join(', ');
    }
    return '';
  }

  /**
   * Pre-filter whitelist validation. Checks if the URL path or Client IP explicitly bypasses WAF.
   * @param {Object} req - The inbound request.
   * @returns {boolean} True if excluded.
   */
  _isExcluded(req) {
    const p = req.path || req.url?.split('?')[0] || '';
    const ip = req.clientIp || this._extractIP(req);

    for (const ex of this.options.excludePaths) {
      if (typeof ex === 'string' && p.startsWith(ex)) return true;
      if (ex instanceof RegExp && ex.test(p)) return true;
    }
    return this.options.excludeIPs.includes(ip);
  }

  /**
   * Reduces the matches array down to its maximum perceived threat tier.
   * @param {Array} matches - The compiled list of threat signatures.
   * @returns {string} Semantic severity ('info', 'critical', etc).
   */
  _getHighestSeverity(matches) {
    let h = 'info', hp = 0;
    for (const m of matches) { 
      const p = SEVERITY_PRIORITY[m.severity] || 0; 
      if (p > hp) { hp = p; h = m.severity; } 
    }
    return h;
  }

  /**
   * Correlates the path context with the Sensitivity Matrix to scale weights.
   * @param {string} path - URL path component.
   * @returns {number} Multiplier float (e.g. 2.5).
   */
  _getEndpointSensitivity(path) {
    for (const rule of ENDPOINT_SENSITIVITY) {
      if (rule.pattern.test(path)) return rule.multiplier;
    }
    return 1.0;
  }

  /**
   * Creates the final JSON block payload sent to attacking clients.
   * @param {Array} matches - Threat array.
   * @param {string} severity - Highest severity tier.
   * @returns {string} Stringified block message mapping.
   */
  getBlockResponse(matches, severity) {
    if (this.options.blockMessage) {
      return typeof this.options.blockMessage === 'function'
        ? this.options.blockMessage(matches) : this.options.blockMessage;
    }
    return JSON.stringify({
      error: 'Request Blocked',
      reason: 'ShieldWall detected a potential security threat',
      severity,
      rules: matches.map(m => m.rule),
      timestamp: new Date().toISOString(),
    });
  }

  /**
   * Retrieves runtime metrics for APM integration.
   * @returns {Object} Metric Map mapping.
   */
  getStats() {
    return {
      ...this.stats,
      uptime: Date.now() - this.stats.startTime,
      rulesLoaded: this.rules.length,
      modulesActive: this.modules.length,
      autoGeneratedRules: this._autoGeneratedHashes.size,
    };
  }

  /**
   * Generates localized .shield rules dynamically if an anomalous payload breaches 
   * strong heuristics. Prevents zero-day spread by mutating to regex blocks.
   * @param {Object} match - The threat trigger.
   * @param {Object} decodedReq - Normalised extraction container.
   */
  _generateAutoRule(match, decodedReq) {
    if (!this.options.autoGenerateRules) return;
    if (match.rule !== 'smart_anomaly_detection' || match.severity !== 'critical') return;

    if (!decodedReq?.rawBody || decodedReq.rawBody.length < 10) return;
    if (this._autoGeneratedHashes.size >= MAX_AUTO_RULES) return;
    if (!match.analysis?.novelIndicators || match.analysis.novelIndicators.length < 3) return;

    const bodyPrefix = decodedReq.rawBody.substring(0, 32);
    let escaped = bodyPrefix.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+');
    if (escaped.length < 8) return;

    const hash = crypto.createHash('md5').update(escaped).digest('hex').substring(0, 8);
    if (this._autoGeneratedHashes.has(hash)) return;

    this._autoGeneratedHashes.add(hash);
    const ruleId = `auto_block_${hash}`;

    const ruleText = `\nrule ${ruleId} : autogenerated {
    meta:
        author = "shieldwall-autodetect"
        description = "Auto-generated from anomaly — review and promote or it expires"
        severity = "high"
        category = "0day_candidate"
        generated_at = "${new Date().toISOString()}"
        ttl_days = ${AUTO_RULE_TTL_DAYS}
    strings:
        $p1 = /${escaped}/i
    condition:
        $p1
}`;

    const rulesFile = path.join(this.options.rulesDir, 'autogenerated.shield');
    try {
      fs.appendFileSync(rulesFile, ruleText, 'utf8');
      this.logger.info(`Auto-generated new shield rule: ${ruleId}`);
      
      this.rules.push(...parseRules(ruleText));
    } catch (err) {
      this.logger.error(`Failed to auto-generate rule: ${err.message}`);
    }
  }

  /**
   * Safely shuts down the orchestrator processes.
   */
  destroy() {
    if (this.reporting) this.reporting.destroy();
    for (const mod of this.modules) {
      if (typeof mod.module?.destroy === 'function') {
        try { mod.module.destroy(); } catch (e) {}
      }
    }
    this.removeAllListeners();
  }
}

module.exports = ShieldWallEngine;
